/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visão;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 55119
 */
public class FormPaciente extends javax.swing.JFrame {

    /**
     * Creates new form FormPaciente
     */
    public FormPaciente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPaciente = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jButtonCadastrar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtCpf = new javax.swing.JTextField();
        txtRg = new javax.swing.JTextField();
        txtFone = new javax.swing.JTextField();
        txtEndereço = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePaciente = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        txtCód = new javax.swing.JTextField();
        Excluir = new javax.swing.JButton();
        Atualizar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastrar Paciente");
        getContentPane().setLayout(null);

        jPanelPaciente.setBackground(new java.awt.Color(0, 0, 0));
        jPanelPaciente.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelPaciente.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 255, 204));
        jLabel2.setText("Nome:");
        jPanelPaciente.add(jLabel2);
        jLabel2.setBounds(10, 30, 50, 20);

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        jPanelPaciente.add(txtNome);
        txtNome.setBounds(50, 30, 220, 20);

        jButtonCadastrar.setBackground(new java.awt.Color(204, 255, 204));
        jButtonCadastrar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonCadastrar.setText("Cadastrar");
        jButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarActionPerformed(evt);
            }
        });
        jPanelPaciente.add(jButtonCadastrar);
        jButtonCadastrar.setBounds(340, 140, 100, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 255, 204));
        jLabel5.setText("CPF:");
        jPanelPaciente.add(jLabel5);
        jLabel5.setBounds(300, 30, 40, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 255, 204));
        jLabel6.setText("Cód:");
        jPanelPaciente.add(jLabel6);
        jLabel6.setBounds(300, 90, 40, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 255, 204));
        jLabel7.setText("Telefone:");
        jPanelPaciente.add(jLabel7);
        jLabel7.setBounds(10, 60, 70, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 255, 204));
        jLabel8.setText("Endereço:");
        jPanelPaciente.add(jLabel8);
        jLabel8.setBounds(10, 90, 70, 20);

        txtCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCpfActionPerformed(evt);
            }
        });
        jPanelPaciente.add(txtCpf);
        txtCpf.setBounds(330, 30, 140, 20);
        jPanelPaciente.add(txtRg);
        txtRg.setBounds(330, 60, 140, 20);
        jPanelPaciente.add(txtFone);
        txtFone.setBounds(70, 60, 200, 20);
        jPanelPaciente.add(txtEndereço);
        txtEndereço.setBounds(70, 90, 200, 20);

        jTablePaciente.setBackground(new java.awt.Color(0, 0, 0));
        jTablePaciente.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTablePaciente.setForeground(new java.awt.Color(204, 255, 204));
        jTablePaciente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Fone", "Endereço", "CPF", "RG", "Cód"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTablePaciente);

        jPanelPaciente.add(jScrollPane1);
        jScrollPane1.setBounds(0, 190, 630, 90);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 255, 204));
        jLabel9.setText("RG:");
        jPanelPaciente.add(jLabel9);
        jLabel9.setBounds(300, 60, 40, 20);
        jPanelPaciente.add(txtCód);
        txtCód.setBounds(330, 90, 140, 20);

        Excluir.setBackground(new java.awt.Color(204, 255, 204));
        Excluir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Excluir.setText("Excluir");
        Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirActionPerformed(evt);
            }
        });
        jPanelPaciente.add(Excluir);
        Excluir.setBounds(20, 140, 90, 30);

        Atualizar.setBackground(new java.awt.Color(204, 255, 204));
        Atualizar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Atualizar.setText("Atualizar");
        Atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtualizarActionPerformed(evt);
            }
        });
        jPanelPaciente.add(Atualizar);
        Atualizar.setBounds(180, 140, 90, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/paciente.jpg"))); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, java.awt.Color.cyan));
        jPanelPaciente.add(jLabel3);
        jLabel3.setBounds(500, 10, 120, 170);

        getContentPane().add(jPanelPaciente);
        jPanelPaciente.setBounds(0, 40, 630, 280);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Cadastro de Paciente:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(190, 10, 200, 22);

        setSize(new java.awt.Dimension(647, 354));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarActionPerformed
        DefaultTableModel Paciente = (DefaultTableModel) jTablePaciente.getModel();
        Object[] dados = {txtNome.getText(), txtFone.getText(), txtEndereço.getText(), txtCpf.getText(),txtRg.getText(), txtCód.getText()};
        Paciente.addRow(dados);
    }//GEN-LAST:event_jButtonCadastrarActionPerformed

    private void txtCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCpfActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirActionPerformed
        if(jTablePaciente.getSelectedRow() != -1){
            DefaultTableModel dtmProntuário = (DefaultTableModel) jTablePaciente.getModel();
            dtmProntuário.removeRow(jTablePaciente.getSelectedRow());
        }else{
            JOptionPane.showMessageDialog(null,"Selecione um produto para Excluir");
        }
    }//GEN-LAST:event_ExcluirActionPerformed

    private void AtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtualizarActionPerformed
        if(jTablePaciente.getSelectedRow() != -1){
            jTablePaciente.setValueAt(txtNome.getText(), jTablePaciente.getSelectedRow(), 0);
            jTablePaciente.setValueAt(txtFone.getText(), jTablePaciente.getSelectedRow(), 1);
            jTablePaciente.setValueAt(txtEndereço.getText(), jTablePaciente.getSelectedRow(), 2);
            jTablePaciente.setValueAt(txtCpf.getText(), jTablePaciente.getSelectedRow(), 3);
            jTablePaciente.setValueAt(txtRg.getText(), jTablePaciente.getSelectedRow(), 4);
            jTablePaciente.setValueAt(txtCód.getText(), jTablePaciente.getSelectedRow(), 5);
        }

    }//GEN-LAST:event_AtualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                FormPaciente meuApp = new FormPaciente();
                meuApp.setVisible(true);
                meuApp.setResizable(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Atualizar;
    private javax.swing.JButton Excluir;
    private javax.swing.JButton jButtonCadastrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanelPaciente;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePaciente;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JTextField txtCód;
    private javax.swing.JTextField txtEndereço;
    private javax.swing.JTextField txtFone;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtRg;
    // End of variables declaration//GEN-END:variables
}
