/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visão;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 55119
 */
public class FormMédico extends javax.swing.JFrame {
    /**
     * Creates new form FormMédico
     */
    public FormMédico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jButtonCadastrar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtCPF = new javax.swing.JTextField();
        txtRG = new javax.swing.JTextField();
        txtFone = new javax.swing.JTextField();
        txtEndereço = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMédico = new javax.swing.JTable();
        txtmed = new javax.swing.JTextField();
        txtEspecialista = new javax.swing.JTextField();
        Fundo = new javax.swing.JLabel();
        Atualizar = new javax.swing.JButton();
        Excluir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro Médico");
        setBackground(new java.awt.Color(0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusTraversalPolicyProvider(true);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 255, 204));
        jLabel2.setText("Nome:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(160, 30, 50, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 255, 204));
        jLabel3.setText("CRM:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(160, 60, 50, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 255, 204));
        jLabel4.setText("Especialização:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(460, 30, 90, 20);

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        jPanel1.add(txtNome);
        txtNome.setBounds(210, 30, 200, 20);

        jButtonCadastrar.setBackground(new java.awt.Color(204, 255, 204));
        jButtonCadastrar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonCadastrar.setText("Cadastrar");
        jButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCadastrar);
        jButtonCadastrar.setBounds(490, 180, 110, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 255, 204));
        jLabel5.setText("CPF:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(460, 60, 40, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 255, 204));
        jLabel6.setText("RG:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(460, 90, 40, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 255, 204));
        jLabel7.setText("Telefone:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(160, 90, 70, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 255, 204));
        jLabel8.setText("Endereço:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(160, 120, 70, 20);

        txtCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCPFActionPerformed(evt);
            }
        });
        jPanel1.add(txtCPF);
        txtCPF.setBounds(530, 60, 140, 20);
        jPanel1.add(txtRG);
        txtRG.setBounds(530, 90, 140, 20);
        jPanel1.add(txtFone);
        txtFone.setBounds(230, 90, 180, 20);
        jPanel1.add(txtEndereço);
        txtEndereço.setBounds(230, 120, 440, 20);

        jTableMédico.setBackground(new java.awt.Color(0, 0, 0));
        jTableMédico.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTableMédico.setForeground(new java.awt.Color(204, 255, 204));
        jTableMédico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "CRM", "Fone", "Endereço", "Especialidade", "CPF", "RG"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableMédico);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(0, 230, 680, 120);
        jPanel1.add(txtmed);
        txtmed.setBounds(210, 60, 200, 20);
        jPanel1.add(txtEspecialista);
        txtEspecialista.setBounds(550, 30, 120, 20);

        Fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/MEDICO.jpg"))); // NOI18N
        Fundo.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, java.awt.Color.cyan));
        jPanel1.add(Fundo);
        Fundo.setBounds(10, 10, 140, 210);

        Atualizar.setBackground(new java.awt.Color(204, 255, 204));
        Atualizar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Atualizar.setText("Atualizar");
        Atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtualizarActionPerformed(evt);
            }
        });
        jPanel1.add(Atualizar);
        Atualizar.setBounds(350, 180, 90, 30);

        Excluir.setBackground(new java.awt.Color(204, 255, 204));
        Excluir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Excluir.setText("Excluir");
        Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirActionPerformed(evt);
            }
        });
        jPanel1.add(Excluir);
        Excluir.setBounds(190, 180, 90, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 40, 680, 350);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Cadastro de Médicos:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(240, 10, 200, 22);

        setSize(new java.awt.Dimension(694, 420));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarActionPerformed
        DefaultTableModel Medico = (DefaultTableModel) jTableMédico.getModel();
        Object[] dados = {txtNome.getText(), txtmed.getText(), txtFone.getText(), txtEndereço.getText(),txtEspecialista.getText(), txtCPF.getText(), txtRG.getText()};
        Medico.addRow(dados);
    }//GEN-LAST:event_jButtonCadastrarActionPerformed

    private void txtCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCPFActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void AtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtualizarActionPerformed
        if(jTableMédico.getSelectedRow() != -1){
            jTableMédico.setValueAt(txtNome.getText(), jTableMédico.getSelectedRow(), 0);
            jTableMédico.setValueAt(txtmed.getText(), jTableMédico.getSelectedRow(), 1);
            jTableMédico.setValueAt(txtFone.getText(), jTableMédico.getSelectedRow(), 2);           
            jTableMédico.setValueAt(txtEndereço.getText(), jTableMédico.getSelectedRow(), 3);
            jTableMédico.setValueAt(txtEspecialista.getText(), jTableMédico.getSelectedRow(), 4);
            jTableMédico.setValueAt(txtCPF.getText(), jTableMédico.getSelectedRow(), 5);
            jTableMédico.setValueAt(txtRG.getText(), jTableMédico.getSelectedRow(), 6);            
        }
    }//GEN-LAST:event_AtualizarActionPerformed

    private void ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirActionPerformed
        if(jTableMédico.getSelectedRow() != -1){
            DefaultTableModel dtmProntuário = (DefaultTableModel) jTableMédico.getModel();
            dtmProntuário.removeRow(jTableMédico.getSelectedRow());
        }else{
            JOptionPane.showMessageDialog(null,"Selecione um produto para Excluir");
        }
    }//GEN-LAST:event_ExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMédico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMédico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMédico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMédico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                FormMédico meuApp = new FormMédico();
                meuApp.setVisible(true);
                meuApp.setResizable(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Atualizar;
    private javax.swing.JButton Excluir;
    private javax.swing.JLabel Fundo;
    private javax.swing.JButton jButtonCadastrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableMédico;
    private javax.swing.JTextField txtCPF;
    private javax.swing.JTextField txtEndereço;
    private javax.swing.JTextField txtEspecialista;
    private javax.swing.JTextField txtFone;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtRG;
    private javax.swing.JTextField txtmed;
    // End of variables declaration//GEN-END:variables

    private void getText() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
